# This software is a part of Isar.
# Copyright (C) 2023 ilbers GmbH

BOOT_SPACE ?= "81920"
MACHINE_SERIAL ?= "serial0"
BAUDRATE_TTY ?= "115200"

IMAGE_FSTYPES ?= "wic"
WKS_FILE ?= "rpi-sdimg"
INSTALLER_WKS_FILE ?= "installer-rpi.wks"

# RPi have custom kernel file names
KERNEL_FILE = "${KERNEL_NAME}.img"

KERNEL_TYPE = "raspios"
KERNEL_IMAGE_PKG ?= "raspberrypi-kernel"
KERNEL_HEADERS_PKG ?= "raspberrypi-kernel-headers"

IMAGE_PREINSTALL += "raspberrypi-sys-mods \
                     raspi-config \
                     systemd-sysv \
                     udev"

IMAGE_PREINSTALL:bullseye += "raspberrypi-bootloader"
IMAGE_PREINSTALL:bookworm += "raspberrypi-bootloader"
IMAGE_PREINSTALL:trixie += "raspi-firmware"

IMAGE_INSTALL += "bootconfig-${MACHINE}"

IMAGER_INSTALL:wic += "parted \
                       dosfstools \
                       mtools \
                       e2fsprogs \
                       bmap-tools"

IMAGER_INSTALL:bullseye:wic += "python3-distutils"
IMAGER_INSTALL:bookworm:wic += "python3-distutils"
IMAGER_INSTALL:trixie:wic += "python3-setuptools"

IMAGE_BOOT_FILES ?= "${IMAGE_ROOTFS}/boot/*.*;./ \
                     ${IMAGE_ROOTFS}/boot/overlays/*;overlays/"

IMAGE_BOOT_FILES:trixie ?= "${IMAGE_ROOTFS}/boot/cmdline.txt;./ \
                            ${IMAGE_ROOTFS}/boot/config.txt;./ \
                            ${IMAGE_ROOTFS}/boot/firmware/*.*;./ \
                            ${IMAGE_ROOTFS}/boot/firmware/overlays/*;overlays/"
