# This software is a part of Isar.
# Copyright (C) 2022,2026 ilbers GmbH

DISTRO_ARCH ?= "armhf"
KERNEL_NAME = "kernel"

include conf/machine/rpi-common.conf

KERNEL_IMAGE_PKG:trixie = "linux-image-rpi-v6"
KERNEL_HEADERS_PKG:trixie = "linux-headers-rpi-v6"
