# This software is a part of Isar.
# Copyright (C) Siemens AG, 2026
#
# SPDX-License-Identifier: MIT

DISTRO_ARCH ?= "amd64"

IMAGE_FSTYPES ?= "wsl"

# Configure rootfs for WSL boot
IMAGE_INSTALL:append = " wsl-config"
# Enable systemd-user session model
IMAGE_PREINSTALL:append = " dbus dbus-user-session"
