# This software is a part of Isar.
# Copyright (C) 2026 ilbers GmbH

MACHINE ?= "rpi-arm-v7l"
DISTRO ?= "raspios-trixie"

KERNEL_IMAGE_PKG = "linux-image-rpi-v7"
KERNEL_HEADERS_PKG = "linux-headers-rpi-v7"
