#!/bin/sh

set -e

readonly ROOTFS="$1"

mknod "${ROOTFS}/dev/random" c 1 8
chmod 640 "${ROOTFS}/dev/random"
chown 0:0 "${ROOTFS}/dev/random"

mknod "${ROOTFS}/dev/urandom" c 1 9
chmod 640 "${ROOTFS}/dev/urandom"
chown 0:0 "${ROOTFS}/dev/urandom"
