#!/bin/sh
# Alternative entrypoint for the kas-based test-container
#
# Copyright (c) Siemens AG, 2026
# SPDX-License-Identifier: MIT

if [ $# -eq 0 ]; then
	exec /container-entrypoint
fi

set -e

# skip "shell [-c]"
if [ $# -gt 1 ]; then
	shift 2
else
	shift 1
fi

clean_rootless_files=0

export args="--max-parallel-tasks=1 --disable-sysinfo"
for arg in $*; do
	case "$arg" in
	--clean)
		rm -rf /work/build/testsuite
		;;
	--debug)
		export showopt="--show=app,test"
		;;
	--shell)
		export start_shell=1
		;;
	--clean-rootless-files)
		clean_rootless_files=1
		;;
	--help)
		cat <<EOF
Usage: run-tests.sh [params] ...

Supported parameters:
  --clean					Purge results of previous test runs before starting.
  --debug					Use '--show=app,test' log settings for avocado.
  --shell					Drop into shell rather than starting tests.
  --clean-rootless-files	Clean up files created by rootless builds with unshare after the tests finish.
  --help					Show this help message.

Any other parameters are passed to "avocado run". Its usage is:

EOF
		avocado run --help
		exit 0
		;;
	*)
		args="$args $arg"
		;;
	esac
done

case "$args" in
*testsuite/*.py*)
	;;
*)
	args="$args testsuite/citest.py"
	;;
esac

case "$args" in
	*"-p rootless=1"*)
		;;
	*)
		clean_rootless_files=0
		;;
esac
export clean_rootless_files

mkdir /isar

busybox syslogd
squid
export http_proxy=http://localhost:3128

# Reuse the existing entrypoint script, exploiting that entry without
# parameters drops us into a shell, rather then calling kas.
echo exit | /container-entrypoint

gosu builder sh -c '
set -e

cleanup_rootless_files()
{
	rc=$?

	if [ "${clean_rootless_files}" = 1 ]; then
		find build \
			\( ! -user "$(whoami)" -type d -prune \) \
			-exec ./scripts/isar-clean-builddir --rootless {} \;
	fi

	exit ${rc}
}

trap cleanup_rootless_files EXIT

base_dir=/work/build/testsuite

mkdir -p ${base_dir}/overlay/upper
mkdir -p ${base_dir}/overlay/work
sudo mount -t overlay overlay -o lowerdir=/repo,upperdir=${base_dir}/overlay/upper,workdir=${base_dir}/overlay/work /isar
sudo mount -o bind ${base_dir} /isar/build

mkdir -p "${HOME}"/.config/avocado
cat <<EOF > "${HOME}"/.config/avocado/avocado.conf
[datadir.paths]
base_dir = ${base_dir}
test_dir = ${base_dir}/tests
data_dir = ${base_dir}/data
logs_dir = ${base_dir}/job-results
EOF

cd /isar

if [ "${start_shell}" = 1 ]; then
	bash
else
	set -x
	avocado ${showopt} run ${args}
fi
'
