#!/bin/sh
set -e

cat /usr/lib/isar-cfg-localepurge/locale.gen \
	>> /etc/locale.gen
cat /usr/lib/isar-cfg-localepurge/locale.default \
	> /etc/default/locale
cat /usr/lib/isar-cfg-localepurge/locale.nopurge \
	> /etc/locale.nopurge

debconf-set-selections /usr/lib/isar-cfg-localepurge/locale.debconf

dpkg-reconfigure -f noninteractive locales

localepurge
